[package]
name = "quant_marketstat_ws"
version = "0.1.0"
edition = "2021"
authors = ["Willy Sajbeni <willy@searchupunk.com>"]
description = "Ferramentas de análise quantitativa com Rust para mercados financeiros."
license = "MIT"


[dependencies]
csv = "1.1"
